version: '3'

services:
  # Base de datos MongoDB
  mongodb:
    image: mongo:latest
    container_name: rifas-mongodb
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - rifas-network
    # Exposici贸n de puerto comentada por seguridad en producci贸n
    # ports:
    #   - "27017:27017"
  
  # Backend (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rifas-backend
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/rifas-los-andes
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-tu_clave_secreta_para_jwt}
      - FRONTEND_URL=${DOMAIN:-https://rifalosandes.es}
    volumes:
      - backend_uploads:/app/uploads
    restart: always
    networks:
      - rifas-network
    # En producci贸n, no exponemos el puerto directamente
    # Solo Nginx accede a este servicio internamente
    # ports:
    #   - "3001:3001"
  
  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rifas-frontend
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${DOMAIN:-https://rifalosandes.es}/api
      - NEXT_PUBLIC_WHATSAPP_NUMBER=${WHATSAPP_NUMBER:-5491155555555}
      - DOMAIN_NAME=${DOMAIN_NAME:-rifalosandes.es}
    restart: always
    networks:
      - rifas-network
    # En producci贸n, no exponemos el puerto directamente
    # Solo Nginx accede a este servicio internamente
    # ports:
    #   - "3000:3000"

  # Nginx como proxy inverso
  nginx:
    image: nginx:alpine
    container_name: rifas-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - backend_uploads:/usr/share/nginx/uploads:ro
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - rifas-network

volumes:
  mongodb_data:
    driver: local
  backend_uploads:
    driver: local

networks:
  rifas-network:
    driver: bridge
